apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hypertrain-relay-us
resources: [../../base]
patches:
  - target: {kind: Namespace, name: hypertrain-relay}
    patch: |-
      - op: replace
        path: /metadata/name
        value: hypertrain-relay-us
  - target: {kind: ConfigMap, name: relay-environment}
    patch: |-
      - op: replace
        path: /data/REGION
        value: us
